unit MtkStatus;

{$IFDEF FPC}
  {$MODE DELPHI}
{$ENDIF}

{ MediaTek BootROM / download-agent status codes.

  Every command answer ends with a 16-bit status word. Values up to $00FF
  mean "accepted"; anything above is a BootROM or DA error, and the vendor
  tools print its name. This unit holds that name table so the log can say
  "error(0x2001 DA_IMAGE_SIG_VERIFY_FAIL)" instead of a bare number.

  Generated from the public MediaTek status-code table
  (bkerler/mtkclient, mtkclient/Library/error.py, GPLv3). }

interface

uses
{$IFDEF FPC}
  SysUtils;
{$ELSE}
  System.SysUtils;
{$ENDIF}

type
  TMtkStatusCode = record
    Code: Word;
    Name: string;
  end;

const
  CMtkStatusCodeCount = 711;

  CMtkStatusCodes: array[0..CMtkStatusCodeCount - 1] of TMtkStatusCode = (
    (Code: $0000; Name: 'OK'),
    (Code: $03E8; Name: 'STOP'),
    (Code: $03E9; Name: 'UNDEFINED_ERROR'),
    (Code: $03EA; Name: 'INVALID_ARGUMENTS'),
    (Code: $03EB; Name: 'INVALID_BBCHIP_TYPE'),
    (Code: $03EC; Name: 'INVALID_EXT_CLOCK'),
    (Code: $03ED; Name: 'INVALID_BMTSIZE'),
    (Code: $03EE; Name: 'GET_DLL_VER_FAIL'),
    (Code: $03EF; Name: 'INVALID_BUF'),
    (Code: $03F0; Name: 'BUF_IS_NULL'),
    (Code: $03F1; Name: 'BUF_LEN_IS_ZERO'),
    (Code: $03F2; Name: 'BUF_SIZE_TOO_SMALL'),
    (Code: $03F3; Name: 'NOT_ENOUGH_STORAGE_SPACE'),
    (Code: $03F4; Name: 'NOT_ENOUGH_MEMORY'),
    (Code: $03F5; Name: 'COM_PORT_OPEN_FAIL'),
    (Code: $03F6; Name: 'COM_PORT_SET_TIMEOUT_FAIL'),
    (Code: $03F7; Name: 'COM_PORT_SET_STATE_FAIL'),
    (Code: $03F8; Name: 'COM_PORT_PURGE_FAIL'),
    (Code: $03F9; Name: 'FILEPATH_NOT_SPECIFIED_YET'),
    (Code: $03FA; Name: 'UNKNOWN_TARGET_BBCHIP'),
    (Code: $03FB; Name: 'SKIP_BBCHIP_HW_VER_CHECK'),
    (Code: $03FC; Name: 'UNSUPPORTED_VER_OF_BOOT_ROM'),
    (Code: $03FD; Name: 'UNSUPPORTED_VER_OF_BOOTLOADER'),
    (Code: $03FE; Name: 'UNSUPPORTED_VER_OF_DA'),
    (Code: $03FF; Name: 'UNSUPPORTED_VER_OF_SEC_INFO'),
    (Code: $0400; Name: 'UNSUPPORTED_VER_OF_ROM_INFO'),
    (Code: $0401; Name: 'SEC_INFO_NOT_FOUND'),
    (Code: $0402; Name: 'ROM_INFO_NOT_FOUND'),
    (Code: $0403; Name: 'CUST_PARA_NOT_SUPPORTED'),
    (Code: $0404; Name: 'CUST_PARA_WRITE_LEN_INCONSISTENT'),
    (Code: $0405; Name: 'SEC_RO_NOT_SUPPORTED'),
    (Code: $0406; Name: 'SEC_RO_WRITE_LEN_INCONSISTENT'),
    (Code: $0407; Name: 'ADDR_N_LEN_NOT_32BITS_ALIGNMENT'),
    (Code: $0408; Name: 'UART_CHKSUM_ERROR'),
    (Code: $0409; Name: 'EMMC_FLASH_BOOT'),
    (Code: $040A; Name: 'NOR_FLASH_BOOT'),
    (Code: $040B; Name: 'NAND_FLASH_BOOT'),
    (Code: $040C; Name: 'UNSUPPORTED_VER_OF_EMI_INFO'),
    (Code: $040D; Name: 'PART_NO_VALID_TABLE'),
    (Code: $040E; Name: 'PART_NO_SPACE_FOUND'),
    (Code: $040F; Name: 'UNSUPPORTED_VER_OF_SEC_CFG'),
    (Code: $0410; Name: 'UNSUPPORTED_OPERATION'),
    (Code: $0411; Name: 'CHKSUM_ERROR'),
    (Code: $0412; Name: 'TIMEOUT'),
    (Code: $07D0; Name: 'SET_META_REG_FAIL'),
    (Code: $07D1; Name: 'SET_FLASHTOOL_REG_FAIL'),
    (Code: $07D2; Name: 'SET_REMAP_REG_FAIL'),
    (Code: $07D3; Name: 'SET_EMI_FAIL'),
    (Code: $07D4; Name: 'DOWNLOAD_DA_FAIL'),
    (Code: $07D5; Name: 'CMD_STARTCMD_FAIL'),
    (Code: $07D6; Name: 'CMD_STARTCMD_TIMEOUT'),
    (Code: $07D7; Name: 'CMD_JUMP_FAIL'),
    (Code: $07D8; Name: 'CMD_WRITE16_MEM_FAIL'),
    (Code: $07D9; Name: 'CMD_READ16_MEM_FAIL'),
    (Code: $07DA; Name: 'CMD_WRITE16_REG_FAIL'),
    (Code: $07DB; Name: 'CMD_READ16_REG_FAIL'),
    (Code: $07DC; Name: 'CMD_CHKSUM16_MEM_FAIL'),
    (Code: $07DD; Name: 'CMD_WRITE32_MEM_FAIL'),
    (Code: $07DE; Name: 'CMD_READ32_MEM_FAIL'),
    (Code: $07DF; Name: 'CMD_WRITE32_REG_FAIL'),
    (Code: $07E0; Name: 'CMD_READ32_REG_FAIL'),
    (Code: $07E1; Name: 'CMD_CHKSUM32_MEM_FAIL'),
    (Code: $07E2; Name: 'JUMP_TO_META_MODE_FAIL'),
    (Code: $07E3; Name: 'WR16_RD16_MEM_RESULT_DIFF'),
    (Code: $07E4; Name: 'CHKSUM16_MEM_RESULT_DIFF'),
    (Code: $07E5; Name: 'BBCHIP_HW_VER_INCORRECT'),
    (Code: $07E6; Name: 'FAIL_TO_GET_BBCHIP_HW_VER'),
    (Code: $07E7; Name: 'AUTOBAUD_FAIL'),
    (Code: $07E8; Name: 'SPEEDUP_BAUDRATE_FAIL'),
    (Code: $07E9; Name: 'LOCK_POWERKEY_FAIL'),
    (Code: $07EA; Name: 'WM_APP_MSG_OUT_OF_RANGE'),
    (Code: $07EB; Name: 'NOT_SUPPORT_MT6205B'),
    (Code: $07EC; Name: 'EXCEED_MAX_DATA_BLOCKS'),
    (Code: $07ED; Name: 'EXTERNAL_SRAM_DETECTION_FAIL'),
    (Code: $07EE; Name: 'EXTERNAL_DRAM_DETECTION_FAIL'),
    (Code: $07EF; Name: 'GET_FW_VER_FAIL'),
    (Code: $07F0; Name: 'CONNECT_TO_BOOTLOADER_FAIL'),
    (Code: $07F1; Name: 'CMD_SEND_DA_FAIL'),
    (Code: $07F2; Name: 'CMD_SEND_DA_CHKSUM_DIFF'),
    (Code: $07F3; Name: 'CMD_JUMP_DA_FAIL'),
    (Code: $07F4; Name: 'CMD_JUMP_BL_FAIL'),
    (Code: $07F5; Name: 'EFUSE_REG_NO_MATCH_WITH_TARGET'),
    (Code: $07F6; Name: 'EFUSE_WRITE_TIMEOUT'),
    (Code: $07F7; Name: 'EFUSE_DATA_PROCESS_ERROR'),
    (Code: $07F8; Name: 'EFUSE_BLOW_ERROR'),
    (Code: $07F9; Name: 'EFUSE_ALREADY_BROKEN'),
    (Code: $07FA; Name: 'EFUSE_BLOW_PARTIAL'),
    (Code: $07FB; Name: 'SEC_VER_FAIL'),
    (Code: $07FC; Name: 'PL_SEC_VER_FAIL'),
    (Code: $07FD; Name: 'SET_WATCHDOG_FAIL'),
    (Code: $07FE; Name: 'EFUSE_VALUE_IS_NOT_ZERO'),
    (Code: $07FF; Name: 'EFUSE_WRITE_TIMEOUT_WITHOUT_EFUSE_VERIFY'),
    (Code: $0800; Name: 'EFUSE_UNKNOW_EXCEPTION_WITHOUT_EFUSE_VERIFY'),
    (Code: $0BB8; Name: 'INT_RAM_ERROR'),
    (Code: $0BB9; Name: 'EXT_RAM_ERROR'),
    (Code: $0BBA; Name: 'SETUP_DRAM_FAIL'),
    (Code: $0BBB; Name: 'SETUP_PLL_ERR'),
    (Code: $0BBC; Name: 'SETUP_EMI_PLL_ERR'),
    (Code: $0BBD; Name: 'DRAM_ABNORMAL_TYPE_SETTING'),
    (Code: $0BBE; Name: 'DRAMC_RANK0_CALIBRATION_FAILED'),
    (Code: $0BBF; Name: 'DRAMC_RANK1_CALIBRATION_FAILED'),
    (Code: $0BC0; Name: 'DRAM_NOT_SUPPORT'),
    (Code: $0BC1; Name: 'RAM_FLOARTING'),
    (Code: $0BC2; Name: 'RAM_UNACCESSABLE'),
    (Code: $0BC3; Name: 'RAM_ERROR'),
    (Code: $0BC4; Name: 'DEVICE_NOT_FOUND'),
    (Code: $0BC5; Name: 'NOR_UNSUPPORTED_DEV_ID'),
    (Code: $0BC6; Name: 'NAND_UNSUPPORTED_DEV_ID'),
    (Code: $0BC7; Name: 'NOR_FLASH_NOT_FOUND'),
    (Code: $0BC8; Name: 'NAND_FLASH_NOT_FOUND'),
    (Code: $0BC9; Name: 'SOC_CHECK_FAIL'),
    (Code: $0BCA; Name: 'NOR_PROGRAM_FAILED'),
    (Code: $0BCB; Name: 'NOR_ERASE_FAILED'),
    (Code: $0BCC; Name: 'NAND_PAGE_PROGRAM_FAILED'),
    (Code: $0BCD; Name: 'NAND_SPARE_PROGRAM_FAILED'),
    (Code: $0BCE; Name: 'NAND_HW_COPYBACK_FAILED'),
    (Code: $0BCF; Name: 'NAND_ERASE_FAILED'),
    (Code: $0BD0; Name: 'TIMEOUT'),
    (Code: $0BD1; Name: 'IN_PROGRESS'),
    (Code: $0BD2; Name: 'SUPERAND_ONLY_SUPPORT_PAGE_READ'),
    (Code: $0BD3; Name: 'SUPERAND_PAGE_PRGRAM_NOT_SUPPORT'),
    (Code: $0BD4; Name: 'SUPERAND_SPARE_PRGRAM_NOT_SUPPORT'),
    (Code: $0BD5; Name: 'SUPERAND_COPYBACK_NOT_SUPPORT'),
    (Code: $0BD6; Name: 'NOR_CMD_SEQUENCE_ERR'),
    (Code: $0BD7; Name: 'NOR_BLOCK_IS_LOCKED'),
    (Code: $0BD8; Name: 'NAND_BLOCK_IS_LOCKED'),
    (Code: $0BD9; Name: 'NAND_BLOCK_DATA_UNSTABLE'),
    (Code: $0BDA; Name: 'NOR_BLOCK_DATA_UNSTABLE'),
    (Code: $0BDB; Name: 'NOR_VPP_RANGE_ERR'),
    (Code: $0BDC; Name: 'INVALID_BEGIN_ADDR'),
    (Code: $0BDD; Name: 'NOR_INVALID_ERASE_BEGIN_ADDR'),
    (Code: $0BDE; Name: 'NOR_INVALID_READ_BEGIN_ADDR'),
    (Code: $0BDF; Name: 'NOR_INVALID_PROGRAM_BEGIN_ADDR'),
    (Code: $0BE0; Name: 'INVALID_RANGE'),
    (Code: $0BE1; Name: 'NOR_PROGRAM_AT_ODD_ADDR'),
    (Code: $0BE2; Name: 'NOR_PROGRAM_WITH_ODD_LENGTH'),
    (Code: $0BE3; Name: 'NOR_BUFPGM_NO_SUPPORT'),
    (Code: $0BE4; Name: 'NAND_UNKNOWN_ERR'),
    (Code: $0BE5; Name: 'NAND_BAD_BLOCK'),
    (Code: $0BE6; Name: 'NAND_ECC_1BIT_CORRECT'),
    (Code: $0BE7; Name: 'NAND_ECC_2BITS_ERR'),
    (Code: $0BE8; Name: 'NAND_SPARE_CHKSUM_ERR'),
    (Code: $0BE9; Name: 'NAND_HW_COPYBACK_DATA_INCONSISTENT'),
    (Code: $0BEA; Name: 'NAND_INVALID_PAGE_INDEX'),
    (Code: $0BEB; Name: 'NFI_NOT_SUPPORT'),
    (Code: $0BEC; Name: 'NFI_CS1_NOT_SUPPORT'),
    (Code: $0BED; Name: 'NFI_16BITS_IO_NOT_SUPPORT'),
    (Code: $0BEE; Name: 'NFB_BOOTLOADER_NOT_EXIST'),
    (Code: $0BEF; Name: 'NAND_NO_GOOD_BLOCK'),
    (Code: $0BF0; Name: 'NAND_UBIIMG_NOT_SPARSEIMAGE'),
    (Code: $0BF1; Name: 'BOOTLOADER_IS_TOO_LARGE'),
    (Code: $0BF2; Name: 'SIBLEY_REWRITE_OBJ_MODE_REGION'),
    (Code: $0BF3; Name: 'SIBLEY_WRITE_B_HALF_IN_CTRL_MODE_REGION'),
    (Code: $0BF4; Name: 'SIBLEY_ILLEGAL_CMD'),
    (Code: $0BF5; Name: 'SIBLEY_PROGRAM_AT_THE_SAME_REGIONS'),
    (Code: $0BF6; Name: 'UART_GET_DATA_TIMEOUT'),
    (Code: $0BF7; Name: 'UART_GET_CHKSUM_LSB_TIMEOUT'),
    (Code: $0BF8; Name: 'UART_GET_CHKSUM_MSB_TIMEOUT'),
    (Code: $0BF9; Name: 'UART_DATA_CKSUM_ERROR'),
    (Code: $0BFA; Name: 'UART_RX_BUF_FULL'),
    (Code: $0BFB; Name: 'UART_RX_BUF_NOT_ENOUGH'),
    (Code: $0BFC; Name: 'FLASH_RECOVERY_BUF_NOT_ENOUGH'),
    (Code: $0BFD; Name: 'HANDSET_SEC_INFO_NOT_FOUND'),
    (Code: $0BFE; Name: 'HANDSET_SEC_INFO_MAC_VERIFY_FAIL'),
    (Code: $0BFF; Name: 'HANDSET_ROM_INFO_NOT_FOUND'),
    (Code: $0C00; Name: 'HANDSET_FAT_INFO_NOT_FOUND'),
    (Code: $0C01; Name: 'OPERATION_UNSUPPORT_FOR_NFB'),
    (Code: $0C02; Name: 'BYPASS_POST_PROCESS'),
    (Code: $0C03; Name: 'NOR_OTP_NOT_SUPPORT'),
    (Code: $0C04; Name: 'NOR_OTP_EXIST'),
    (Code: $0C05; Name: 'NOR_OTP_LOCKED'),
    (Code: $0C06; Name: 'NOR_OTP_GETSIZE_FAIL'),
    (Code: $0C07; Name: 'NOR_OTP_READ_FAIL'),
    (Code: $0C08; Name: 'NOR_OTP_PROGRAM_FAIL'),
    (Code: $0C09; Name: 'NOR_OTP_LOCK_FAIL'),
    (Code: $0C0A; Name: 'NOR_OTP_LOCK_CHECK_STATUS_FAIL'),
    (Code: $0C0B; Name: 'BLANK_FLASH'),
    (Code: $0C0C; Name: 'CODE_AREA_IS_BLANK'),
    (Code: $0C0D; Name: 'SEC_RO_AREA_IS_BLANK'),
    (Code: $0C0E; Name: 'NOR_OTP_UNLOCKED'),
    (Code: $0C0F; Name: 'UNSUPPORTED_BBCHIP'),
    (Code: $0C10; Name: 'FAT_NOT_EXIST'),
    (Code: $0C11; Name: 'EXT_SRAM_NOT_FOUND'),
    (Code: $0C12; Name: 'EXT_DRAM_NOT_FOUND'),
    (Code: $0C13; Name: 'MT_PIN_LOW'),
    (Code: $0C14; Name: 'MT_PIN_HIGH'),
    (Code: $0C15; Name: 'MT_PIN_SHORT'),
    (Code: $0C16; Name: 'MT_BUS_ERROR'),
    (Code: $0C17; Name: 'MT_ADDR_NOT_2BYTE_ALIGNMENT'),
    (Code: $0C18; Name: 'MT_ADDR_NOT_4BYTE_ALIGNMENT'),
    (Code: $0C19; Name: 'MT_SIZE_NOT_2BYTE_ALIGNMENT'),
    (Code: $0C1A; Name: 'MT_SIZE_NOT_4BYTE_ALIGNMENT'),
    (Code: $0C1B; Name: 'MT_DEDICATED_PATTERN_ERROR'),
    (Code: $0C1C; Name: 'MT_INC_PATTERN_ERROR'),
    (Code: $0C1D; Name: 'MT_DEC_PATTERN_ERROR'),
    (Code: $0C1E; Name: 'NFB_BLOCK_0_IS_BAD'),
    (Code: $0C1F; Name: 'CUST_PARA_AREA_IS_BLANK'),
    (Code: $0C20; Name: 'ENTER_RELAY_MODE_FAIL'),
    (Code: $0C21; Name: 'ENTER_RELAY_MODE_IS_FORBIDDEN_AFTER_META'),
    (Code: $0C22; Name: 'NAND_PAGE_READ_FAILED'),
    (Code: $0C23; Name: 'NAND_IMAGE_BLOCK_NO_EXIST'),
    (Code: $0C24; Name: 'NAND_IMAGE_LIST_NOT_EXIST'),
    (Code: $0C25; Name: 'MBA_RESOURCE_NO_EXIST_IN_TARGET'),
    (Code: $0C26; Name: 'MBA_PROJECT_VERSION_NO_MATCH_WITH_TARGET'),
    (Code: $0C27; Name: 'MBA_UPDATING_RESOURCE_NO_EXIST_IN_TARGET'),
    (Code: $0C28; Name: 'MBA_UPDATING_RESOURCE_SIZE_EXCEED_IN_TARGET'),
    (Code: $0C29; Name: 'NAND_BIN_SIZE_EXCEED_MAX_SIZE'),
    (Code: $0C2A; Name: 'NAND_EXCEED_CONTAINER_LIMIT'),
    (Code: $0C2B; Name: 'NAND_REACH_END_OF_FLASH'),
    (Code: $0C2C; Name: 'NAND_OTP_NOT_SUPPORT'),
    (Code: $0C2D; Name: 'NAND_OTP_EXIST'),
    (Code: $0C2E; Name: 'NAND_OTP_LOCKED'),
    (Code: $0C2F; Name: 'NAND_OTP_LOCK_FAIL'),
    (Code: $0C30; Name: 'NAND_OTP_UNLOCKED'),
    (Code: $0C31; Name: 'OTP_NOT_SUPPORT'),
    (Code: $0C32; Name: 'OTP_EXIST'),
    (Code: $0C33; Name: 'OTP_LOCKED'),
    (Code: $0C34; Name: 'OTP_GETSIZE_FAIL'),
    (Code: $0C35; Name: 'OTP_READ_FAIL'),
    (Code: $0C36; Name: 'OTP_PROGRAM_FAIL'),
    (Code: $0C37; Name: 'OTP_LOCK_FAIL'),
    (Code: $0C38; Name: 'OTP_LOCK_CHECK_STATUS_FAIL'),
    (Code: $0C39; Name: 'OTP_UNLOCKED'),
    (Code: $0C3A; Name: 'SEC_RO_ILLEGAL_MAGIC_TAIL'),
    (Code: $0C3B; Name: 'HANDSET_FOTA_INFO_NOT_FOUND'),
    (Code: $0C3C; Name: 'HANDSET_UA_INFO_NOT_FOUND'),
    (Code: $0C3D; Name: 'SB_FSM_INVALID_INFO'),
    (Code: $0C3E; Name: 'NFB_TARGET_DUAL_BL_PAIRED_VERSION_NOT_MATCHED_WITH_MAUI'),
    (Code: $0C3F; Name: 'NFB_TARGET_DUAL_BL_FEATURE_COMBINATION_NOT_MATCHED_WITH_MAUI'),
    (Code: $0C40; Name: 'NFB_TARGET_IS_SINGLE_BL_BUT_PC_NOT'),
    (Code: $0C41; Name: 'NFB_TARGET_IS_DUAL_BL_BUT_PC_NOT'),
    (Code: $0C42; Name: 'NOR_TARGET_BL_PAIRED_VERSION_NOT_MATCHED_WITH_MAUI'),
    (Code: $0C43; Name: 'NOR_TARGET_BL_FEATURE_COMBINATION_NOT_MATCHED_WITH_MAUI'),
    (Code: $0C44; Name: 'NOR_TARGET_IS_NOT_NEW_BL_BUT_PC_IS'),
    (Code: $0C45; Name: 'NOR_TARGET_IS_NEW_BL_BUT_PC_NOT'),
    (Code: $0C46; Name: 'DOWNLOAD_BOOTLOADER_FLASH_DEV_IS_NONE'),
    (Code: $0C47; Name: 'DOWNLOAD_BOOTLOADER_FLASH_DEV_IS_NOT_SUPPORTED'),
    (Code: $0C48; Name: 'DOWNLOAD_BOOTLOADER_BEGIN_ADDR_OVERLAPS_WITH_PREVIOUS_BOUNDARY'),
    (Code: $0C49; Name: 'UPDATE_BOOTLOADER_EXIST_MAGIC_NOT_MATCHED'),
    (Code: $0C4A; Name: 'UPDATE_BOOTLOADER_FILE_TYPE_NOT_MATCHED'),
    (Code: $0C4B; Name: 'UPDATE_BOOTLOADER_FILE_SIZE_EXCEEDS_BOUNDARY_ADDR'),
    (Code: $0C4C; Name: 'UPDATE_BOOTLOADER_BEGIN_ADDR_NOT_MATCHED'),
    (Code: $0C4D; Name: 'EMMC_FLASH_NOT_FOUND'),
    (Code: $0C4E; Name: 'EMMC_FW_VER_CHECK_FAIL'),
    (Code: $0C4F; Name: 'SDMMC_FLASH_NOT_FOUND'),
    (Code: $0C50; Name: 'SDMMC_CONFIG_FAILED'),
    (Code: $0C51; Name: 'SDMMC_READ_FAILED'),
    (Code: $0C52; Name: 'SDMMC_WRITE_FAILED'),
    (Code: $0C53; Name: 'SDMMC_ERR_CRC'),
    (Code: $0C54; Name: 'SDMMC_ERR_TIMEOUT'),
    (Code: $0C55; Name: 'SDMMC_UNSUPPORTED'),
    (Code: $0C56; Name: 'DSPBL_CHECK_PLATFORM_FAILED'),
    (Code: $0C57; Name: 'UFS_FLASH_NOT_FOUND'),
    (Code: $0C58; Name: 'UFS_CONFIG_FAILED'),
    (Code: $0C59; Name: 'UFS_READ_FAILED'),
    (Code: $0C5A; Name: 'UFS_WRITE_FAILED'),
    (Code: $0C5B; Name: 'UFS_ERR_TIMEOUT'),
    (Code: $0C5C; Name: 'UFS_UNSUPPORTED'),
    (Code: $0C5D; Name: 'UFS_OTP_NOT_SUPPORT'),
    (Code: $0C5E; Name: 'UFS_OTP_EXIST'),
    (Code: $0C5F; Name: 'UFS_OTP_LOCKED'),
    (Code: $0C60; Name: 'UFS_OTP_LOCK_FAIL'),
    (Code: $0C61; Name: 'UFS_OTP_UNLOCKED'),
    (Code: $0C62; Name: 'HANDSET_SEC_CFG_NOT_FOUND'),
    (Code: $0C63; Name: 'EMMC_OTP_NOT_SUPPORT'),
    (Code: $0C64; Name: 'EMMC_OTP_EXIST'),
    (Code: $0C65; Name: 'EMMC_OTP_LOCKED'),
    (Code: $0C66; Name: 'EMMC_OTP_LOCK_FAIL'),
    (Code: $0C67; Name: 'EMMC_OTP_UNLOCKED'),
    (Code: $0C68; Name: 'READ_IMEI_PID_SWV_NOT_SUPPORT'),
    (Code: $0C69; Name: 'NFI_EMPTY_PAGE'),
    (Code: $0C6A; Name: 'INVALID_STORAGE_TYPE'),
    (Code: $0C6B; Name: 'SEND_CMD_FAIL'),
    (Code: $0C6C; Name: 'READ_CMD_ACK_FAIL'),
    (Code: $0C6D; Name: 'READ_FLASH_STATUS_INFO_FAIL'),
    (Code: $0C6E; Name: 'PL_VALIDATION_FAIL'),
    (Code: $0C6F; Name: 'STORAGE_NOT_MATCH'),
    (Code: $0C70; Name: 'CHIP_TYPE_NOT_MATCH'),
    (Code: $0C71; Name: 'EXCEED_MAX_PARTITION_COUNT'),
    (Code: $1000; Name: 'CRYPTO_INIT_FAIL'),
    (Code: $1001; Name: 'CRYPTO_DEINIT_FAIL'),
    (Code: $1002; Name: 'CRYPTO_MODE_INVALID'),
    (Code: $1003; Name: 'CRYPTO_KEY_INVALID'),
    (Code: $1004; Name: 'CRYPTO_DATA_UNALIGNED'),
    (Code: $1770; Name: 'CALLBACK_SLA_CHALLENGE_FAIL'),
    (Code: $1771; Name: 'SLA_WRONG_AUTH_FILE'),
    (Code: $1772; Name: 'SLA_INVALID_AUTH_FILE'),
    (Code: $1773; Name: 'SLA_CHALLENGE_FAIL'),
    (Code: $1774; Name: 'SLA_FAIL'),
    (Code: $1775; Name: 'DAA_FAIL'),
    (Code: $1776; Name: 'SBC_FAIL'),
    (Code: $1777; Name: 'SF_SECURE_VER_CHECK_FAIL'),
    (Code: $1778; Name: 'SF_HANDSET_SECURE_CUSTOM_NAME_NOT_MATCH'),
    (Code: $1779; Name: 'SF_FTCFG_LOCKDOWN'),
    (Code: $177A; Name: 'SF_CODE_DOWNLOAD_FORBIDDEN'),
    (Code: $177B; Name: 'SF_CODE_READBACK_FORBIDDEN'),
    (Code: $177C; Name: 'SF_CODE_FORMAT_FORBIDDEN'),
    (Code: $177D; Name: 'SF_SEC_RO_DOWNLOAD_FORBIDDEN'),
    (Code: $177E; Name: 'SF_SEC_RO_READBACK_FORBIDDEN'),
    (Code: $177F; Name: 'SF_SEC_RO_FORMAT_FORBIDDEN'),
    (Code: $1780; Name: 'SF_FAT_DOWNLOAD_FORBIDDEN'),
    (Code: $1781; Name: 'SF_FAT_READBACK_FORBIDDEN'),
    (Code: $1782; Name: 'SF_FAT_FORMAT_FORBIDDEN'),
    (Code: $1783; Name: 'SF_RESTRICTED_AREA_ACCESS_FORBIDDEN'),
    (Code: $1784; Name: 'SECURE_CUSTOM_NAME_NOT_MATCH_BETWEEN_AUTH_AND_DL_HANDLE'),
    (Code: $1785; Name: 'DOWNLOAD_FILE_IS_CORRUPTED'),
    (Code: $1786; Name: 'NOT_SUPPORT'),
    (Code: $1787; Name: 'BOOTLOADER_IMAGE_SIGNATURE_FAIL'),
    (Code: $1788; Name: 'BOOTLOADER_ELDER_SW_VERSION_CANNOT_BE_DOWNLOADED'),
    (Code: $1789; Name: 'BOOTLOADER_IMAGE_NO_SIGNATURE'),
    (Code: $178A; Name: 'BOOTLOADER_CORRUPTED_SCATTER_FILE'),
    (Code: $178B; Name: 'SECURE_USB_DL_NO_MAUI_IN_SCATTER_FILE'),
    (Code: $178C; Name: 'SEND_CERT_FAIL'),
    (Code: $178D; Name: 'SEND_AUTH_FAIL'),
    (Code: $178E; Name: 'GET_SEC_CONFIG_FAIL'),
    (Code: $178F; Name: 'GET_ME_ID_FAIL'),
    (Code: $1790; Name: 'GET_HW_SW_VER_FAIL'),
    (Code: $1791; Name: 'GET_HW_CODE_FAIL'),
    (Code: $1792; Name: 'ROM_INFO_NOT_FOUND'),
    (Code: $1793; Name: 'ROM_INFO_ID_MISMATCH'),
    (Code: $1794; Name: 'SEC_CTRL_ID_MISMATCH'),
    (Code: $1795; Name: 'SEC_KEY_ID_MISMATCH'),
    (Code: $1796; Name: 'SECURE_USB_DL_FAIL'),
    (Code: $1797; Name: 'SECURE_USB_DL_CHECK_TARGET_STATUS_FAIL'),
    (Code: $1798; Name: 'SECURE_USB_DL_SEND_CHIP_STATUS_FAIL'),
    (Code: $1799; Name: 'SECURE_USB_DL_DISABLED'),
    (Code: $179A; Name: 'SECURE_USB_DL_ENABLED'),
    (Code: $179B; Name: 'SECURE_USB_DL_IMAGE_PUBLIC_N_KEY_READ_FAIL'),
    (Code: $179C; Name: 'SECURE_USB_DL_IMAGE_PUBLIC_E_KEY_READ_FAIL'),
    (Code: $179D; Name: 'SECURE_USB_DL_IMAGE_SIGN_HEADER_NOT_FOUND'),
    (Code: $179E; Name: 'SECURE_USB_DL_IMGAE_SIGNATURE_VERIFY_FAIL'),
    (Code: $179F; Name: 'SECURE_USB_DL_IMAGE_HASH_FAIL'),
    (Code: $17A0; Name: 'SECURE_USB_DL_IMAGE_NOT_FOUND'),
    (Code: $17A1; Name: 'SECURE_USB_DL_INVALID_IMAGE_ARGUMENT'),
    (Code: $17A2; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_INIT_FAIL'),
    (Code: $17A3; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_WRITE_IMAGE_NAME_FAIL'),
    (Code: $17A4; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_WRITE_IMAGE_NAME_LEN_FAIL'),
    (Code: $17A5; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_WRITE_TYPE_FAIL'),
    (Code: $17A6; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_WRITE_HEADER_FAIL'),
    (Code: $17A7; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_WRITE_IMAGE_OFFSET_FAIL'),
    (Code: $17A8; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_WRITE_SIGNATURE_HASH_FAIL'),
    (Code: $17A9; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_GET_CHECK_RESULT_FAIL'),
    (Code: $17AA; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_DOWNLOAD_IMAGE_INVALID'),
    (Code: $17AB; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_UNKNOWN_CHECK_RESULT'),
    (Code: $17AC; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_WRONG_OPERATION'),
    (Code: $17AD; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_INVALID_HEADER_LENGTH'),
    (Code: $17AE; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_INVALID_IMAGE_OFFSET'),
    (Code: $17AF; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_INVALID_SIGNATURE_LENGTH'),
    (Code: $17F0; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_SIGNATURE_LENGTH_TOO_LARGE'),
    (Code: $17F1; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_IMAGE_NAME_LENGTH_TOO_LONG'),
    (Code: $17F2; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_EXT_HEADER_TOO_LARGE'),
    (Code: $17F3; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_EXT_HEADER_OFFSET_INVALID'),
    (Code: $17F4; Name: 'SECURE_USB_DL_IMAGE_INFO_CHECK_CMD_EXT_HEADER_SELF_COPY_FAIL'),
    (Code: $17F5; Name: 'SEC_CFG_NOT_EXIST'),
    (Code: $17F6; Name: 'SEC_CFG_WRITE_CMD_INIT_FAIL'),
    (Code: $17F7; Name: 'SEC_CFG_WRONG_MAGIC_NUMBER'),
    (Code: $17F8; Name: 'SEC_CFG_IS_FULL_CANNOT_ADD_NEW_IMAGE'),
    (Code: $17F9; Name: 'SEC_CFG_IMAGE_NOT_FOUND_SO_CANNOT_UPDATE'),
    (Code: $17FA; Name: 'SEC_CFG_IMAGE_CUST_NAME_MISMATCH'),
    (Code: $17FB; Name: 'SEC_CFG_IMAGE_CANNOT_ROLL_BACK_SW_LOAD'),
    (Code: $17FC; Name: 'SEC_CFG_IMAGE_EXIST_CANNOT_CREATE_MEW_FILE'),
    (Code: $17FD; Name: 'SEC_CFG_WRITE_FAIL_CFG_NOT_EXIST'),
    (Code: $17FE; Name: 'SEC_CFG_WRITE_FAIL_MAGIC_INCORRECT'),
    (Code: $17FF; Name: 'SEC_CFG_WRITE_FAIL_CANNOT_WRITE_TO_FIRST_BLOCK'),
    (Code: $1800; Name: 'SEC_CFG_WRITE_FAIL_YAFFS2_POST_PROCESS_FAIL'),
    (Code: $1801; Name: 'SEC_CFG_WRITE_FAIL_NAND_DEVICE'),
    (Code: $1802; Name: 'SEC_CFG_WRITE_FAIL_CANNOT_READ_BACK'),
    (Code: $1803; Name: 'SEC_CFG_WRITE_FAIL_READ_BACK_MAGIC_INCORRECT'),
    (Code: $1804; Name: 'SEC_CFG_WRITE_FAIL_READ_BACK_ID_INCORRECT'),
    (Code: $1805; Name: 'SEC_CFG_WRITE_FAIL_READ_BACK_STATUS_INCORRECT'),
    (Code: $1806; Name: 'SEC_CFG_WRITE_FAIL_READ_BACK_END_PATTERN_INCORRECT'),
    (Code: $1807; Name: 'SEC_CFG_WRITE_FAIL_SEC_CFG_CANNOT_OVERWRITE_NEXT_PARTITION'),
    (Code: $1808; Name: 'SEC_CFG_WRITE_FAIL_NAND_NOT_DETECTED'),
    (Code: $1809; Name: 'SEC_CFG_WRITE_FAIL_EMMC_NOT_DETECTED'),
    (Code: $180A; Name: 'SEC_CFG_WRITE_FAIL_EMMC_DEVICE'),
    (Code: $180B; Name: 'SEC_CFG_WRITE_FAIL_NAND_PAGE_SIZE_NOT_SUPPORT'),
    (Code: $180C; Name: 'SEC_CFG_WRITE_FAIL_NAND_FIND_GOOD_BLK_FAIL'),
    (Code: $180D; Name: 'SEC_CFG_WRITE_FAIL_NAND_ERASE_FAIL'),
    (Code: $180E; Name: 'SEC_CFG_WRITE_FAIL_UNKNOWN_DEVIE_TYPE'),
    (Code: $180F; Name: 'SEC_CFG_READ_FAIL_NAND_NOT_DETECTED'),
    (Code: $1810; Name: 'SEC_CFG_READ_FAIL_EMMC_NOT_DETECTED'),
    (Code: $1811; Name: 'SEC_CFG_READ_FAIL_EMMC_DEVICE'),
    (Code: $1812; Name: 'SEC_CFG_READ_FAIL_NAND_PAGE_SIZE_NOT_SUPPORT'),
    (Code: $1813; Name: 'SEC_CFG_READ_FAIL_NAND_FIND_GOOD_BLK_FAIL'),
    (Code: $1814; Name: 'SEC_CFG_READ_FAIL_UNKNOWN_DEVIE_TYPE'),
    (Code: $1815; Name: 'SEC_CFG_READ_FAIL_NAND_LOGICAL_READ_FAIL'),
    (Code: $1816; Name: 'SEC_CFG_EXT_REGION_SPACE_OVERFLOW'),
    (Code: $1817; Name: 'SECURE_USB_DL_ROM_INFO_UPDATE_REQUEST_FAIL'),
    (Code: $1818; Name: 'SECURE_USB_DL_DA_RETURN_INVALID_TYPE'),
    (Code: $1819; Name: 'SECURE_USB_DL_MOVE_IMAGE_HEADER_TO_END_FAIL'),
    (Code: $181A; Name: 'SECURE_USB_DL_NO_NEED_TO_MOVE_IMAGE_HEADER'),
    (Code: $181B; Name: 'SECURE_USB_DL_NO_NEED_TO_REMOVE_IMAGE_HEADER_AND_SIG'),
    (Code: $181C; Name: 'CIPHER_DATA_UNALIGNED'),
    (Code: $181D; Name: 'CIPHER_MODE_INVALID'),
    (Code: $181E; Name: 'CIPHER_KEY_INVALID'),
    (Code: $181F; Name: 'CIPHER_INIT_FAIL'),
    (Code: $1820; Name: 'CIPHER_ROM_NOT_LOADED'),
    (Code: $1821; Name: 'CIPHER_DEC_FAIL'),
    (Code: $1822; Name: 'CIPHER_ENC_TEST_FAIL'),
    (Code: $1823; Name: 'AES_VER_INVALID'),
    (Code: $1824; Name: 'INVALID_IMGDEC_CFG'),
    (Code: $1825; Name: 'IMGDEC_INVALID_FORCE_DEC_PARAM'),
    (Code: $1826; Name: 'IMGDEC_INVALID_AES_KEY_SIZE'),
    (Code: $1827; Name: 'IMGDEC_FAIL_IMAGE_NOT_ENCRYPTED'),
    (Code: $1828; Name: 'IMGDEC_INIT_FAIL_FTH_IS_NULL'),
    (Code: $1829; Name: 'IMGDEC_INIT_FAIL_DECH_IS_NULL'),
    (Code: $182A; Name: 'INIDEC_FAIL_INI_NOT_ENCRYPTED'),
    (Code: $182B; Name: 'INIDEC_INVALID_AES_KEY_SIZE'),
    (Code: $182C; Name: 'INVALID_PROJECT'),
    (Code: $182D; Name: 'SECRO_ANTICLONE_LENGTH_INVALID'),
    (Code: $182E; Name: 'SECRO_HASH_INCORRECT'),
    (Code: $182F; Name: 'SECRO_ENCRYPT_FAIL'),
    (Code: $1830; Name: 'AC_REGION_NOT_FOUND_IN_SECROIMG'),
    (Code: $1B58; Name: 'EPP_FAIL'),
    (Code: $1B59; Name: 'EPP_EXT_DRAM_NOT_FOUND'),
    (Code: $1B5A; Name: 'EPP_EXT_DRAM_INIT_FAIL'),
    (Code: $1B5B; Name: 'EPP_NO_EMI_CONFIG_PARAM_FAIL'),
    (Code: $1D00; Name: 'ADDRESS_TOO_HIGH_80000000'),
    (Code: $1D01; Name: 'ADDRESS_TOO_HIGH_40000000'),
    (Code: $1D02; Name: 'INVALID_ADDRESS'),
    (Code: $1D0C; Name: 'NO_AUTH_NEEDED'),
    (Code: $1D0D; Name: 'SLA_ERROR'),
    (Code: $1D0E; Name: 'DA_OVERLAP'),
    (Code: $1D0F; Name: 'DA_INVALID_JUMP_ADDR'),
    (Code: $1D10; Name: 'DA_EXCEED_MAX_DA_BLOCKS'),
    (Code: $1D11; Name: 'DA_ADDR_NOT_16BITS_ALIGNED'),
    (Code: $1D12; Name: 'DA_INVALID_ADDR_AND_LEN'),
    (Code: $1D13; Name: 'DA_LEN_IS_ZERO'),
    (Code: $1D14; Name: 'DA_SIG_LEN_EXCEED_DA_LEN'),
    (Code: $1D15; Name: 'DA_SIG_LEN_IS_ZERO_AND_DAA_ACTIVE'),
    (Code: $1D16; Name: 'DA_NOT_EXIST'),
    (Code: $1D17; Name: 'DA_BLOCKS_INCONSISTENT_WITH_TOOL_AUTH'),
    (Code: $1D21; Name: 'DA_VERSION_NOT_SUPPORTED'),
    (Code: $2000; Name: 'AUTH_IMAGE_VERIFY_FAIL'),
    (Code: $2001; Name: 'DA_IMAGE_SIG_VERIFY_FAIL'),
    (Code: $2002; Name: 'DA_IMAGE_NO_MEM_FAIL'),
    (Code: $2003; Name: 'DA_INIT_KEY_FAIL'),
    (Code: $2004; Name: 'IMG_INIT_KEY_FAIL'),
    (Code: $2005; Name: 'HASH_IMAGE_FAIL'),
    (Code: $2006; Name: 'DA_RELOCATE_SIZE_NOT_ENOUGH'),
    (Code: $2711; Name: 'PL_MODE_UNSUPPORTED'),
    (Code: $2712; Name: 'PL_MODE_FORBIDDEN'),
    (Code: $2713; Name: 'PL_MODE_INVALID_ARGUMETS'),
    (Code: $2714; Name: 'PL_READ_FAIL'),
    (Code: $2715; Name: 'PL_WRITE_FAIL'),
    (Code: $2716; Name: 'PL_READ_TIMEOUT'),
    (Code: $2717; Name: 'PL_WRITE_TIMEOUT'),
    (Code: $2718; Name: 'PL_DISC_CMD_NEEDED'),
    (Code: $3000; Name: 'LIB_SEC_CFG_NOT_EXIST'),
    (Code: $3001; Name: 'LIB_VER_INVALID'),
    (Code: $3002; Name: 'LIB_SEC_CFG_ERASE_FAIL'),
    (Code: $3003; Name: 'LIB_SEC_CFG_CANNOT_WRITE'),
    (Code: $3004; Name: 'LIB_SEC_CFG_END_PATTERN_NOT_EXIST'),
    (Code: $3005; Name: 'LIB_SEC_CFG_STATUS_INVALID'),
    (Code: $3006; Name: 'LIB_SEC_CFG_READ_SIZE_NOT_ENOUGH'),
    (Code: $3007; Name: 'LIB_SEC_CFG_RSA_KEY_INIT_FAIL'),
    (Code: $4000; Name: 'IMG_VERIFY_THIS_IMG_INFO_NOT_EXIST'),
    (Code: $4001; Name: 'IMG_VERIFY_HASH_COMPARE_FAIL'),
    (Code: $4002; Name: 'IMG_VERIFY_NO_SPACE_ADD_IMG_INFO'),
    (Code: $4003; Name: 'SEC_DL_TOKEN_NOT_FOUND_IN_IMG'),
    (Code: $4004; Name: 'SEC_DL_FLOW_ERROR'),
    (Code: $4005; Name: 'IMG_VERIFY_INVALID_IMG_INFO_ATTR'),
    (Code: $4006; Name: 'IMG_SECROIMG_NOT_FOUND'),
    (Code: $4007; Name: 'IMG_READ_FAIL'),
    (Code: $4008; Name: 'IMG_VERIFY_SIGNATURE_FAIL'),
    (Code: $4009; Name: 'IMG_SIGN_FORMAT_NOT_MATCH'),
    (Code: $400A; Name: 'IMG_EXTENSION_HDR_NOT_FOUND'),
    (Code: $400B; Name: 'IMG_EXTENSION_MAGIC_WRONG'),
    (Code: $400C; Name: 'IMG_EXTENSION_TYPE_NOT_SUPPORT'),
    (Code: $400D; Name: 'IMG_EXTENSION_HASH_CAL_FAIL'),
    (Code: $5000; Name: 'IMG_LOCK_TABLE_NOT_EXIST'),
    (Code: $5001; Name: 'IMG_LOCK_ALL_LOCK'),
    (Code: $5002; Name: 'IMG_LOCK_NO_SPACE_ADD_LOCK_INFO'),
    (Code: $5003; Name: 'IMG_LOCK_THIS_IMG_INFO_NOT_EXIST'),
    (Code: $5004; Name: 'IMG_LOCK_MAGIC_ERROR'),
    (Code: $5A5B; Name: 'DA_IN_BLACKLIST'),
    (Code: $6000; Name: 'SBC_KEY_NOT_FOUND'),
    (Code: $6001; Name: 'BR_SEC_CFG_NOT_FOUND'),
    (Code: $6002; Name: 'ERR_PUBK_NOT_INITIALIZED'),
    (Code: $6003; Name: 'SHA256_OP_FAIL'),
    (Code: $6004; Name: 'ERR_PSS_CHK_FAIL'),
    (Code: $6005; Name: 'ERR_SIG_CHK_FAIL'),
    (Code: $7000; Name: 'REGION_INVALID_INCLUDE'),
    (Code: $7001; Name: 'REGION_INVALID_OVERLAP'),
    (Code: $7002; Name: 'REGION_INVALID_OVERFLOW'),
    (Code: $7003; Name: 'DA_INVALID_LOCATION'),
    (Code: $7004; Name: 'DA_INVALID_LENGTH'),
    (Code: $7015; Name: 'DAA_Security_Error_Signature'),
    (Code: $7017; Name: 'DAA_Security_Error'),
    (Code: $7024; Name: 'DAA_SIG_VERIFY_FAILED'),
    (Code: $8000; Name: 'INVALID_SIG_SZ'),
    (Code: $8001; Name: 'INVALID_PADDING_SZ'),
    (Code: $9000; Name: 'SW_ID_MISMATCH'),
    (Code: $9001; Name: 'INVALID_IMG_TYPE'),
    (Code: $9002; Name: 'BUF_NOT_ENOUGH_FOR_CERT'),
    (Code: $9003; Name: 'IMG_NOT_FOUND'),
    (Code: $9004; Name: 'IMG_HDR_HASH_VFY_FAIL'),
    (Code: $9005; Name: 'IMG_HASH_VFY_FAIL'),
    (Code: $9006; Name: 'INVALID_OID_SZ'),
    (Code: $9007; Name: 'INVALID_OID_BUF_SZ'),
    (Code: $9008; Name: 'END_OF_CERT'),
    (Code: $9009; Name: 'CERT_OBJ_ID_NOT_MATCH'),
    (Code: $900A; Name: 'CERT_OBJ_SZ_NOT_MATCH'),
    (Code: $900B; Name: 'CERT_TRAVERSE_UNKNOWN_MODE'),
    (Code: $900C; Name: 'INVALID_OID_IDX'),
    (Code: $900D; Name: 'OID_NOT_FOUND'),
    (Code: $900E; Name: 'OBJ_NOT_FOUND'),
    (Code: $900F; Name: 'E_KEY_LEN_NOT_MATCH'),
    (Code: $9010; Name: 'E_KEY_NOT_MATCH'),
    (Code: $9011; Name: 'N_KEY_LEN_NOT_MATCH'),
    (Code: $9012; Name: 'N_KEY_NOT_MATCH'),
    (Code: $9013; Name: 'PUBK_AUTH_FAIL'),
    (Code: $9014; Name: 'INVALID_IMG_HDR'),
    (Code: $9015; Name: 'NOT_EXPECTED_IMG'),
    (Code: $A000; Name: 'CERT_IMG_VER_NOT_SYNC'),
    (Code: $A001; Name: 'IMAGE_IMG_VER_NOT_SYNC'),
    (Code: $A002; Name: 'IMG_VER_ROLLBACK'),
    (Code: $A003; Name: 'OTP_FIELD_NOT_ENOUGH'),
    (Code: $A004; Name: 'OTP_REG_BIT_CONFIG_WRONG'),
    (Code: $A005; Name: 'OTP_WRITE_FAIL'),
    (Code: $C0010001; Name: 'Error'),
    (Code: $C0010002; Name: 'Abort'),
    (Code: $C0010003; Name: 'Unsupported command'),
    (Code: $C0010004; Name: 'Unsupported ctrl code'),
    (Code: $C0010005; Name: 'Protocol error'),
    (Code: $C0010006; Name: 'Protocol buffer overflow'),
    (Code: $C0010007; Name: 'Insufficient buffer'),
    (Code: $C0010008; Name: 'USB SCAN error'),
    (Code: $C0010009; Name: 'Invalid hsession'),
    (Code: $C001000A; Name: 'Invalid session'),
    (Code: $C001000B; Name: 'Invalid stage'),
    (Code: $C001000C; Name: 'Not implemented'),
    (Code: $C001000D; Name: 'File not found'),
    (Code: $C001000E; Name: 'Open file error'),
    (Code: $C001000F; Name: 'Write file error'),
    (Code: $C0010010; Name: 'Read file error'),
    (Code: $C0010011; Name: 'Create File error / Unsupported Version'),
    (Code: $C0020001; Name: 'Rom info not found'),
    (Code: $C0020002; Name: 'Cust name not found'),
    (Code: $C0020003; Name: 'Device not supported'),
    (Code: $C0020004; Name: 'DL forbidden'),
    (Code: $C0020005; Name: 'Img too large'),
    (Code: $C0020006; Name: 'PL verify fail'),
    (Code: $C0020007; Name: 'Image verify fail'),
    (Code: $C0020008; Name: 'Hash operation fail'),
    (Code: $C0020009; Name: 'Hash binding check fail'),
    (Code: $C002000A; Name: 'Invalid buf'),
    (Code: $C002000B; Name: 'Binding hash not available'),
    (Code: $C002000C; Name: 'Write data not allowed'),
    (Code: $C002000D; Name: 'Format not allowed'),
    (Code: $C002000E; Name: 'SV5 public key auth failed'),
    (Code: $C002000F; Name: 'SV5 hash verify failed'),
    (Code: $C0020010; Name: 'SV5 RSA OP failed'),
    (Code: $C0020011; Name: 'SV5 RSA verify failed'),
    (Code: $C0020012; Name: 'SV5 GFH not found'),
    (Code: $C0020013; Name: 'Cert1 invalid'),
    (Code: $C0020014; Name: 'Cert2 invalid'),
    (Code: $C0020015; Name: 'Imghdr invalid'),
    (Code: $C0020016; Name: 'Sig size invalid'),
    (Code: $C0020017; Name: 'RSA pss op fail'),
    (Code: $C0020018; Name: 'Cert auth failed'),
    (Code: $C0020019; Name: 'Public key auth mismatch n size'),
    (Code: $C002001A; Name: 'Public key auth mismatch e size'),
    (Code: $C002001B; Name: 'Public key auth mismatch n'),
    (Code: $C002001C; Name: 'Public key auth mismatch e'),
    (Code: $C002001D; Name: 'Public key auth mismatch hash'),
    (Code: $C002001E; Name: 'Cert obj not found'),
    (Code: $C002001F; Name: 'Cert oid not found'),
    (Code: $C0020020; Name: 'Cert out of range'),
    (Code: $C0020021; Name: 'Oid doesn''t match'),
    (Code: $C0020022; Name: 'Length doesn''t match'),
    (Code: $C0020023; Name: 'ASN1 unknown op'),
    (Code: $C0020024; Name: 'OID index out of range'),
    (Code: $C0020025; Name: 'OID too large'),
    (Code: $C0020026; Name: 'Public key size mismatch'),
    (Code: $C0020027; Name: 'SWID mismatch'),
    (Code: $C0020028; Name: 'Hash size mismatch'),
    (Code: $C0020029; Name: 'IMGHDR type mismatch'),
    (Code: $C002002A; Name: 'IMG type mismatch'),
    (Code: $C002002B; Name: 'IMGHDR hash verify failed'),
    (Code: $C002002C; Name: 'IMG has verify failed'),
    (Code: $C002002D; Name: 'Anti rollback violation'),
    (Code: $C002002E; Name: 'SECCFG not found'),
    (Code: $C002002F; Name: 'SECCFG magic incorrect'),
    (Code: $C0020030; Name: 'SECCFG invalid'),
    (Code: $C0020031; Name: 'Cipher mode invalid'),
    (Code: $C0020032; Name: 'Cipher key invalid'),
    (Code: $C0020033; Name: 'Cipher data unaligned'),
    (Code: $C0020034; Name: 'GFH file info not found'),
    (Code: $C0020035; Name: 'GFH anti clone not found'),
    (Code: $C0020036; Name: 'GFH sec cfg not found'),
    (Code: $C0020037; Name: 'Unsupported source type'),
    (Code: $C0020038; Name: 'Cust name mismatch'),
    (Code: $C0020039; Name: 'Invalid address'),
    (Code: $C0020040; Name: 'Certificate version not synced'),
    (Code: $C0020041; Name: 'Signature not synced'),
    (Code: $C0020042; Name: 'Ext AllInOne Signature rejected'),
    (Code: $C0020043; Name: 'Ext AllInOne Signature missing'),
    (Code: $C0020044; Name: 'Comm Key is not set'),
    (Code: $C0020045; Name: 'DevInfo Check failed'),
    (Code: $C0020046; Name: 'Bootimg count overflow'),
    (Code: $C0020047; Name: 'Signature not found'),
    (Code: $C0020048; Name: 'Bootimg special handle'),
    (Code: $C0020049; Name: 'Remote Seucrity policy disabled'),
    (Code: $C002004A; Name: 'RSA OAEP fail'),
    (Code: $C002004B; Name: 'Insufficient buffer'),
    (Code: $C002004C; Name: 'DA Anti-Rollback error'),
    (Code: $C002004D; Name: 'Get OTP value fail'),
    (Code: $C002004E; Name: 'Invalid unit size'),
    (Code: $C002004F; Name: 'Invalid group idx'),
    (Code: $C0020050; Name: 'Img version overflow'),
    (Code: $C0020051; Name: 'Otp table not initialized'),
    (Code: $C0020052; Name: 'Invalid Partition name'),
    (Code: $C0020053; Name: 'DA version Anti-Rollback error'),
    (Code: $C0020054; Name: 'Invalid msg size'),
    (Code: $C0020055; Name: 'Security level unsupported'),
    (Code: $C0020056; Name: 'Security level mismatch'),
    (Code: $C0020057; Name: 'Fault injection error'),
    (Code: $C0020058; Name: 'Public Key hash group invalid - too many root keys'),
    (Code: $C0020059; Name: 'Security level too large'),
    (Code: $C002005A; Name: 'Security config is formatted'),
    (Code: $C002005B; Name: 'Security config unknown error'),
    (Code: $C002005C; Name: 'Lockstate seccfg fail'),
    (Code: $C002005D; Name: 'Lockstate custom fail'),
    (Code: $C002005E; Name: 'Lockstate inconsistent'),
    (Code: $C0030001; Name: 'Scatter file invalid'),
    (Code: $C0030002; Name: 'DA file invalid'),
    (Code: $C0030003; Name: 'DA selection error'),
    (Code: $C0030004; Name: 'Preloader invalid'),
    (Code: $C0030005; Name: 'EMI hdr invalid'),
    (Code: $C0030006; Name: 'Storage mismatch'),
    (Code: $C0030007; Name: 'Invalid parameters'),
    (Code: $C0030008; Name: 'Invalid GPT'),
    (Code: $C0030009; Name: 'Invalid PMT'),
    (Code: $C003000A; Name: 'Layout changed'),
    (Code: $C003000B; Name: 'Invalid format param'),
    (Code: $C003000C; Name: 'Unknown storage section type'),
    (Code: $C003000D; Name: 'Unknown scatter field'),
    (Code: $C003000E; Name: 'Partition tbl doesn''t exist'),
    (Code: $C003000F; Name: 'Scatter hw chip id mismatch'),
    (Code: $C0030010; Name: 'SEC cert file not found'),
    (Code: $C0030011; Name: 'SEC auth file not found'),
    (Code: $C0030012; Name: 'SEC auth file needed'),
    (Code: $C0030013; Name: 'EMI containter file not found'),
    (Code: $C0030014; Name: 'Scatter file not found'),
    (Code: $C0030015; Name: 'Xml file op error'),
    (Code: $C0030016; Name: 'Unsupported page size'),
    (Code: $C0030017; Name: 'EMI info length offset invalid'),
    (Code: $C0030018; Name: 'EMI info length invalid'),
    (Code: $C0040001; Name: 'Unsupported operation'),
    (Code: $C0040002; Name: 'Thread error'),
    (Code: $C0040003; Name: 'Checksum error'),
    (Code: $C0040004; Name: 'Unknown sparse'),
    (Code: $C0040005; Name: 'Unknown sparse chunk type'),
    (Code: $C0040006; Name: 'Partition not found'),
    (Code: $C0040007; Name: 'Read parttbl failed'),
    (Code: $C0040008; Name: 'Exceeded max partition number'),
    (Code: $C0040009; Name: 'Unknown storage type'),
    (Code: $C004000A; Name: 'Dram Test failed'),
    (Code: $C004000B; Name: 'Exceed available range'),
    (Code: $C004000C; Name: 'Write sparse image failed'),
    (Code: $C0040030; Name: 'MMC error'),
    (Code: $C0040040; Name: 'Nand error'),
    (Code: $C0040041; Name: 'Nand in progress'),
    (Code: $C0040042; Name: 'Nand timeout'),
    (Code: $C0040043; Name: 'Nand bad block'),
    (Code: $C0040044; Name: 'Nand erase failed'),
    (Code: $C0040045; Name: 'Nand page program failed'),
    (Code: $C0040050; Name: 'EMI setting version error'),
    (Code: $C0040060; Name: 'UFS error'),
    (Code: $C0040100; Name: 'DA OTP not supported'),
    (Code: $C0040102; Name: 'DA OTP lock failed'),
    (Code: $C0040200; Name: 'EFUSE unknown error'),
    (Code: $C0040201; Name: 'EFUSE write timeout without verify'),
    (Code: $C0040202; Name: 'EFUSE blown'),
    (Code: $C0040203; Name: 'EFUSE revert bit'),
    (Code: $C0040204; Name: 'EFUSE blown partly'),
    (Code: $C0040205; Name: 'EFUSE invalid argument'),
    (Code: $C0040206; Name: 'EFUSE value is not zero'),
    (Code: $C0040207; Name: 'EFUSE blown incorrect data'),
    (Code: $C0040208; Name: 'EFUSE broken'),
    (Code: $C0040209; Name: 'EFUSE blow error'),
    (Code: $C004020A; Name: 'EFUSE data process error'),
    (Code: $C004020B; Name: 'EFUSE unlock bpkey error'),
    (Code: $C004020C; Name: 'EFUSE create list error'),
    (Code: $C004020D; Name: 'EFUSE write register error'),
    (Code: $C004020E; Name: 'EFUSE padding type mismatch'),
    (Code: $C0050001; Name: 'Device ctrl exception'),
    (Code: $C0050002; Name: 'Shutdown Cmd exception'),
    (Code: $C0050003; Name: 'Download exception'),
    (Code: $C0050004; Name: 'Upload exception'),
    (Code: $C0050005; Name: 'Ext Ram exception'),
    (Code: $C0050006; Name: 'Notify Switch Usb Speed exception'),
    (Code: $C0050007; Name: 'Read data exception'),
    (Code: $C0050008; Name: 'Write data exception'),
    (Code: $C0050009; Name: 'Format exception'),
    (Code: $C005000A; Name: 'OTP operation exception'),
    (Code: $C005000B; Name: 'Switch usb exception'),
    (Code: $C005000C; Name: 'Write efuse exception'),
    (Code: $C005000D; Name: 'Read efuse exception'),
    (Code: $C0060001; Name: 'Brom start cmd/connect not preloader failed'),
    (Code: $C0060002; Name: 'Brom get bbchip hw ver failed'),
    (Code: $C0060003; Name: 'Brom cmd send da failed'),
    (Code: $C0060004; Name: 'Brom cmd jump da failed'),
    (Code: $C0060005; Name: 'Brom cmd failed'),
    (Code: $C0060006; Name: 'Brom stage callback failed'),
    (Code: $C0070001; Name: 'DA Version mismatch'),
    (Code: $C0070002; Name: 'DA not found'),
    (Code: $C0070003; Name: 'DA section not found'),
    (Code: $C0070004; Name: 'DA hash mismatch'),
    (Code: $C0070005; Name: 'DA exceed max num'),
  );

{ True when a status word means "the device accepted the command". }
function StatusIsOk(AStatus: Word): Boolean;
{ 'DA_IMAGE_SIG_VERIFY_FAIL', or '' when the code is not in the table. }
function StatusName(AStatus: Word): string;
{ What the log prints: 'OK', '0x2001 DA_IMAGE_SIG_VERIFY_FAIL'. }
function StatusText(AStatus: Word): string;

implementation

function StatusIsOk(AStatus: Word): Boolean;
begin
  Result := AStatus <= $00FF;
end;

function StatusName(AStatus: Word): string;
var
  Lo, Hi, Mid: Integer;
begin
  Result := '';
  Lo := 0;
  Hi := CMtkStatusCodeCount - 1;
  while Lo <= Hi do
  begin
    Mid := (Lo + Hi) div 2;
    if CMtkStatusCodes[Mid].Code = AStatus then
      Exit(CMtkStatusCodes[Mid].Name)
    else if CMtkStatusCodes[Mid].Code < AStatus then
      Lo := Mid + 1
    else
      Hi := Mid - 1;
  end;
end;

function StatusText(AStatus: Word): string;
begin
  if AStatus = 0 then
    Result := 'OK'
  else
  begin
    Result := '0x' + IntToHex(AStatus, 4);
    if StatusName(AStatus) <> '' then
      Result := Result + ' ' + StatusName(AStatus);
  end;
end;

end.
